# Generated by Django 5.0.3 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на вакансию'),
        ),
    ]
