# Generated by Django 5.0.3 on 2024-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='stack',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='vacancies.stacktool', verbose_name='Стек'),
        ),
    ]
