# Generated by Django 5.0.3 on 2024-03-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Можно работать удаленно'),
        ),
    ]
