# Generated by Django 5.0.3 on 2024-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancy_is_remote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobplace',
            name='speciality',
            field=models.CharField(choices=[('devops', 'DevOps-инженер'), ('analytics', 'Аналитик'), ('data-scientist', 'Дата-сайентист'), ('mentor', 'Преподаватель'), ('developer', 'Программист'), ('lead', 'Руководитель группы разработки'), ('sysadmin', 'Системный администратор'), ('qa', 'Тестировщик')], max_length=255, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='speciality',
            field=models.CharField(choices=[('devops', 'DevOps-инженер'), ('analytics', 'Аналитик'), ('data-scientist', 'Дата-сайентист'), ('mentor', 'Преподаватель'), ('developer', 'Программист'), ('lead', 'Руководитель группы разработки'), ('sysadmin', 'Системный администратор'), ('qa', 'Тестировщик')], max_length=255, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='stacktool',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'без опыта'), ('between_1_2', 'от 1 до 3 лет'), ('between_3_5', 'от 3 до 5 лет'), ('more_than_5', 'Более 5 лет')], max_length=255, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='speciality',
            field=models.CharField(choices=[('devops', 'DevOps-инженер'), ('analytics', 'Аналитик'), ('data-scientist', 'Дата-сайентист'), ('mentor', 'Преподаватель'), ('developer', 'Программист'), ('lead', 'Руководитель группы разработки'), ('sysadmin', 'Системный администратор'), ('qa', 'Тестировщик')], max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'company', 'text', 'speciality', 'language')},
        ),
    ]
